language: java
sudo: false
install: true

jdk:
- openjdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key:
    secure: "wsm0jIU/665dLJZmq1deikTD1JcTPsC7sBpGLMu6EhHkggNnExeZyDMkohPm2LDItU8p+qExaK+hVThjTFr3r4ZOZZ10uVdfP2gzc3FG3cgBxaK4+NbSTCKWg47UaFZbLdZq2Y0IxykWKQ705ngbmllKSiUA+uYWGrv9vIhdJ+0HkIZeSeetX+TQ6WtHnzAS65hb2baPSonwHUAjOOJge4pyfGdJdMQQfnF5aPuzsdNDr9pcQTanx+C5gBcqaIWkAEXOJG80d9pmc7kCRmzMZuqGeRT8FLQtyzt0CGrgd+7m7EYvGdRQvvNX8VICaM++nOFzDTcC3Z4whSYfVN0L/gQEq7ZMTZ1GiXrbRqY4z/i6xG58uXqA0j+QDAoRTHSUOpwR3wNWwMQQ/uN9j0yoVeHTivH5Hh2UtmB4Q5ribGvOXqk1PJDqbpFaNTIpZol7Elnp8cLDbPyvxZXRx6ITdTi1pXuJjPjmKg4beNIBXw1/N2Mjopogn2u+PbpvGFuNxDCBtltgD35Wn0TLbdxKcMwOSK4jAThZ/CpXk5z75A9rWY9fj4wpypy9u9HSsePMYEmFrwb+vOkfd3CSentEvrZlJVySXFqG/8trJyrRjq+33reCtAL6oGxyIm3YN7sBQG/HoKBD+Qn3s2uBEdz440zdUQaG8k7zyCGXsM7CfSI="
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true

script:
- chmod +x gradlew
- ./gradlew shadowJar
